antpolis:
  type: "nodejs-app"
  deploymentType: "helm"
  layer: "application"

app:
  url: 
  environment: 
  port: 

# Ingress Configuration (Always enabled)
ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  domains:
    # - name: "{{ .Values.app.url }}"
    #   paths:
    #     - path: "/"
    #       pathType: "Prefix"
    #       service:
    #         name: "{{ .Release.Name }}-service"
    #         port: {{ .Values.app.port }}
    #     - path: "/api"
    #       pathType: "Prefix"
    #       service:
    #         name: "{{ .Release.Name }}-api"
    #         port: 8080
    # - name: "admin.{{ .Values.app.url }}"
    #   paths:
    #     - path: "/"
    #       pathType: "Prefix"
    #       service:
    #         name: "{{ .Release.Name }}-admin"
    #         port: 3000

# User Ingress Overrides
# This section allows you to override or add to the default ingress configuration
# Example:
userIngress:
  # className: nginx-user  # Optional: override ingress class
 # annotations:  # Optional: add or override annotations
 #   custom.annotation: "value"
 # domains:  # Optional: add additional domains
 #   - name: "custom.example.com"
 #     paths:
 #       - path: "/"
 #         pathType: "Prefix"
 #         service:
 #           name: "custom-service"
 #           port: 8080

# Optional Components Configuration
persistence:
  enabled: false
  volumes:
    # wp-uploads:
    #   enabled: false
    #   size: 10Gi
    #   storageClass: ""
    #   hostPath: "/data/projects/{{ .Values.app.url }}/wp-uploads"
    #   mountPath: "/var/www/html/wp-content/uploads"
    #   claim:
    #     enabled: false
    #     size: 10Gi
    #     storageClass: ""
    # wp-plugins:
    #   enabled: false
    #   size: 5Gi
    #   storageClass: ""
    #   hostPath: "/data/projects/{{ .Values.app.url }}/wp-plugins"
    #   mountPath: "/var/www/html/wp-content/plugins"
    #   claim:
    #     enabled: false
    #     size: 5Gi
    #     storageClass: ""

# User Persistence Overrides
# This section allows you to override or add to the default persistence configuration
# Example:
userPersistence:
 enabled: false  # Optional: override enabled state
 volumes:  # Optional: add or override volumes
   

configMap:
  enabled: false
  value:
    files:
      
    env:
      

secrets:
  enabled: false
  value:


# User ConfigMap Overrides
# This section allows you to override or add to the default configmap configuration
# Example:
userConfigMap:
 enabled: false  # Optional: override enabled state
 values:
   files:
     
   env:

# User Secrets Overrides
# This section allows you to override or add to the default secrets configuration
# Example:
userSecrets:
 enabled: false  # Optional: override enabled state
 values:
   