apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "antpolis-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      {{- range .Values.ingress.domains }}
      - {{ .name }}
      secretName: {{ $.Release.Name }}-ssl-tls
  rules:
  {{- range .Values.ingress.domains }}
  - host: {{ .name }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .service.name }}
            port:
              number: {{ .service.port }}
      {{- end }}
  {{- end }}
{{- end }}