apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "antpolis-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      {{- if and .Values.app.url  }}
      - {{ .Values.app.url }}
      {{- end }}
      {{- range .Values.ingress.domains }}
      - {{ .name }}
      secretName: {{ $.Release.Name }}-ssl-tls
      {{- end }}
  rules:
  {{- if and .Values.app.url .Values.app.port }}
  - host: "{{ .Values.app.url }}"
    http:
      paths:  
        path: "/"
        pathType: "Prefix"
        service:
          name: "{{ .Release.Name }}-service"
          port: {{ .Values.app.port }}
  {{- end }}
  {{- range .Values.ingress.domains }}
  - host: {{ .name }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .service.name }}
            port:
              number: {{ .service.port }}
      {{- end }}
  {{- end }}