# Application Type Configuration
antpolis:
  # Allowed values: nodejs-app, dotnet-app, java-app, nextJS, vue
  type: "nodejs-app"
  deploymentType: "helm"
  # Allowed values: api-backend, frontend, grpc-backend
  layer: "api-backend"

# Application Settings
app:
  url:
  # Allowed values: prod, staging, dev, tipsy, stable
  environment:
  port: 

docker:
  tag:
  repo:
  imagePullSecrets:
    - name: dockerhub

# Ingress Configuration (Always enabled)
ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  domains:
    # - name: "{{ .Values.app.url }}"
    #   paths:
    #     - path: "/"
    #       pathType: "Prefix"
    #       service:
    #         name: "{{ .Release.Name }}-service"
    #         port: {{ .Values.app.port }}
    #     - path: "/api"
    #       pathType: "Prefix"
    #       service:
    #         name: "{{ .Release.Name }}-api"
    #         port: 8080
    # - name: "admin.{{ .Values.app.url }}"
    #   paths:
    #     - path: "/"
    #       pathType: "Prefix"
    #       service:
    #         name: "{{ .Release.Name }}-admin"
    #         port: 3000

# Optional Components Configuration
persistence:
  enabled: false
  volumes:
    # wp-uploads:
    #   enabled: false
    #   size: 10Gi
    #   storageClass: ""
    #   hostPath: "/data/projects/{{ .Values.app.url }}/wp-uploads"
    #   mountPath: "/var/www/html/wp-content/uploads"
    #   claim:
    #     enabled: false
    #     size: 10Gi
    #     storageClass: ""
    # wp-plugins:
    #   enabled: false
    #   size: 5Gi
    #   storageClass: ""
    #   hostPath: "/data/projects/{{ .Values.app.url }}/wp-plugins"
    #   mountPath: "/var/www/html/wp-content/plugins"
    #   claim:
    #     enabled: false
    #     size: 5Gi
    #     storageClass: ""

configMap:
  enabled: false
  value:
    files:
      
    env:
      

secrets:
  enabled: false
  value: